config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("select2/", include("django_select2.urls")),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import (TaskAtWork, TaskClose, TaskCreateView, TaskDetailView,
                        TaskListView, TaskRefuse, TaskUpdateView, TaskWhishes,
                        ask_gemini_api, clear_context, stream_gemini)
from users.views import telegram_webhook

app_name = MainConfig.name


urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>", TaskDetailView.as_view(), name="task_detail"),
    path("task_update/<int:pk>", TaskUpdateView.as_view(), name="task_update"),
    path("task/work/<int:pk>", TaskAtWork.as_view(), name="task_at_work"),
    path("task/close/<int:pk>", TaskClose.as_view(), name="task_close"),
    path("task/whishes/<int:pk>", TaskWhishes.as_view(), name="task_whishes"),
    path("task/refuse/<int:pk>", TaskRefuse.as_view(), name="task_refuse"),
    path("webhook/", telegram_webhook, name="webhook"),
    path("ask-gemini/", ask_gemini_api, name="ask_gemini_api"),
    path("stream-gemini/", stream_gemini, name="stream_gemini"),
    path("clear-context/", clear_context, name="clear_context"),
    # path("whatsapp_webhook/", whatsapp_webhook, name="whatsapp_webhook"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (CustomLoginView, CustomPasswordChangeView,
                         RecoveryPasswordView, UserCreateView, UserProfileView,
                         UserUpdateView, developer ) # email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", CustomLoginView.as_view(template_name="login.html"), name="login"),
    path(
        "activate_account/",
        CustomLoginView.as_view(template_name="activate.html"),
        name="activate_account",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    # path("activate/<str:token>/", email_verification, name="activate"),
    path("recovery/", RecoveryPasswordView.as_view(), name="recovery"),
    path(
        "profile/<int:pk>/", UserProfileView.as_view(), name="profile"
    ),  # Для показа профиля
    path(
        "profile/update/<int:pk>/", UserUpdateView.as_view(), name="profile_update"
    ),  # Для редактирования профиля
    path(
        "profile/password_change/",
        CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("developer/", developer, name="developer"),
]

main/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (Http404, HttpResponseRedirect, JsonResponse,
                         StreamingHttpResponse)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (CreateView, DetailView, ListView, UpdateView,
                                  View)
from django.views.generic.detail import SingleObjectMixin

from main.forms import CommentaryTaskForm, ModeratorTaskForm, TaskForm
from main.models import CATEGORY_CHOICES, STATUS_CHOICES, Task
from users.models import CITY_CHOICES
from users.services import process_gemini_for_web, stream_gemini_response
from users.tasks import (close_task, coordinator_task, new_comment_task,
                         new_executor, new_task, new_task_admin, new_watcher,
                         work_task)

from .models import User


class TaskListView(LoginRequiredMixin, ListView):
    paginate_by = 20
    login_url = "users:login"
    model = Task

    def get_queryset(self):
        user = self.request.user
        queryset = Task.objects.all()

        # Фильтрация по статусу
        status_filter = self.request.GET.get("status")
        if status_filter:
            queryset = queryset.filter(status=status_filter)

        # Фильтрация по городу
        city_filter = self.request.GET.get("city")
        if city_filter:
            queryset = queryset.filter(author__city=city_filter)

        my_task_filter = self.request.GET.get("my_tasks")
        if my_task_filter:
            queryset = queryset.filter(executor=user)

        category_filter = self.request.GET.get("category")
        if category_filter:
            queryset = queryset.filter(category=category_filter)

        show_all_filter = self.request.GET.get("show_all")
        if status_filter != "close":
            if not show_all_filter:
                queryset = queryset.filter().exclude(status="close")

        # Логика фильтрации для разных типов пользователей
        if user.is_superuser or user.is_staff:
            return queryset
        elif user.is_admin:
            return (
                queryset.filter(author__city=user.city, executor__isnull=True)
                | queryset.filter(executor=user)
                | queryset.filter(coordinator=user)
                | queryset.filter(watcher=user)
            )
        else:
            return (
                queryset.filter(author=user)
                | queryset.filter(coordinator=user)
                | queryset.filter(watcher=user)
            )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["tasks"] = queryset
        context["statuses"] = STATUS_CHOICES
        context["categories"] = CATEGORY_CHOICES
        context["cities"] = CITY_CHOICES
        context["total_task_count"] = queryset.count()
        return context

    def render_to_response(self, context, **response_kwargs):
        # Если запрос AJAX, вернуть только частичный шаблон
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return render(self.request, "main/partials/task_list_dynamic.html", context)
        # Иначе вернуть полный шаблон
        return super().render_to_response(context, **response_kwargs)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = "task"

    def dispatch(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs["pk"])
        user = request.user

        # Проверка суперпользователя и персонала
        if user.is_superuser or user.is_staff:
            return super().dispatch(request, *args, **kwargs)

        # Проверка для админа
        if getattr(user, "is_admin", False):  # безопасный доступ к атрибуту
            if (
                task.author and task.author.city == user.city and task.executor is None
            ) or task.executor == user:
                return super().dispatch(request, *args, **kwargs)

        # Проверка для обычных пользователей
        if (
            user in {task.author, task.coordinator, task.executor}
            or user in task.watcher.all()
        ):
            return super().dispatch(request, *args, **kwargs)

        raise Http404

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        context["comments"] = task.comments.all()  # Получение комментариев
        context["form"] = CommentaryTaskForm()  # Форма для нового комментария
        return context

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        form = CommentaryTaskForm(request.POST)
        host = self.request.get_host()
        url = f"https://{host}/task/{task.pk}"
        if task.status != "close":
            if form.is_valid():
                comment = form.save(commit=False)
                comment.task = task
                comment.author = request.user
                comment.save()

                # Определяем получателей
                recipients = []
                if task.executor and task.executor != request.user:
                    recipients.append(task.executor.email)
                if task.coordinator and task.coordinator != request.user:
                    recipients.append(task.coordinator.email)
                if task.author and task.author != request.user:
                    recipients.append(task.author.email)
                if task.watcher:
                    recipients.extend(
                        task.watcher.exclude(id=request.user.id).values_list(
                            "email", flat=True
                        )
                    )

                # Убираем дублирующиеся email-адреса
                recipients = list(set(recipients))
                print(recipients)

                # Отправляем задачу
                new_comment_task.delay(task.title, url, recipients)

                return HttpResponseRedirect(reverse("main:task_detail", args=[task.pk]))
            else:
                return self.get(request, *args, **kwargs)


class TaskCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy("main:task_detail", kwargs={"pk": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        task = form.save(commit=False)
        user = self.request.user
        task.author = user
        task.status = "new"
        task.save()

        # Рассылка уведомлений
        host = self.request.get_host()
        url = f"https://{host}/task/{task.pk}"
        admin_emails = []
        watcher_emails = []
        new_task.delay(task.title, task.pk, url, task.author.email)
        # Заполняем список наблюдателей
        if task.watcher:
            watcher_emails.extend(
                task.watcher.exclude(id=user.id).values_list("email", flat=True)
            )
        # Заполняем список админов по городу
        for admin in User.objects.filter(is_admin=True, city=task.author.city):
            if admin.email:
                admin_emails.append(admin.email)

        if task.executor:
            new_executor.delay(
                task.title,
                task.pk,
                url,
                task.executor.email,
            )
        else:
            new_task_admin.delay(task.title, task.pk, url, admin_emails)
        if task.watcher:
            new_watcher.delay(
                task.title,
                task.pk,
                url,
                watcher_emails,
            )
        if task.coordinator:
            coordinator_task.delay(task.title, task.pk, url, [task.coordinator.email])
        return super().form_valid(form)

    def form_invalid(self, form):
        """Показать ошибки для каждого поля и общие ошибки"""
        for field, errors in form.errors.items():
            if field in form.fields:
                for error in errors:
                    messages.error(self.request, f"{form.fields[field].label}: {error}")
            else:
                # Для общих ошибок (из clean)
                for error in errors:
                    messages.error(self.request, error)

        return super().form_invalid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy("main:task_detail", kwargs={"pk": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        form_class = self.get_form_class()
        if form_class in [TaskForm, ModeratorTaskForm]:
            kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        task = form.save(commit=False)  # Сохраняем форму, но не коммитим в БД
        old_task = Task.objects.get(pk=task.pk)  # Получаем старую версию объекта из БД

        host = self.request.get_host()
        url = f"https://{host}/task/{task.pk}"

        # Проверяем изменение координатора
        if (
            old_task.coordinator != task.coordinator
            and task.coordinator
            and not task.wishes
        ):
            coordinator_task.delay(task.title, task.pk, url, [task.coordinator.email])

        # Проверяем изменение статуса на "complete"
        if old_task.status != "complete" and task.status == "complete":
            close_task(task.title, task.commentary, task.author.email)

main/templates/includes/inc_header.html
{% load static i18n %}
<link href="{% static 'css/theme.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">

<header class="navbar navbar-expand-lg px-3 py-2 theme-navbar">
  <div class="container-fluid">
    <!-- Логотип -->
    <a href="/" class="navbar-brand d-flex align-items-center">
      <img src="{% static 'img/logo.png' %}" alt="Logo" style="height: 50px;">
    </a>

    <!-- Кнопка переключения меню на мобильных -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Основное меню -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a href="/" class="nav-link menu-btn">{% translate "Главная" %}</a>
        </li>

        <!-- Выпадающий список NAS -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle menu-btn" href="#" id="nasDropdown" role="button" data-bs-toggle="dropdown">
            Список ссылок
          </a>
          <ul class="dropdown-menu theme-dropdown">
            <li><a class="dropdown-item hover-bg" href="#" target="_blank">выбор 1</a></li>
            <li><a class="dropdown-item hover-bg" href="#" target="_blank">выбор 2</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link menu-btn" target="_blank">Ссылка</a>
        </li>
      </ul>

      <!-- Переключатель темы -->
        <div class="form-check form-switch me-3">
          <input class="form-check-input theme-toggle-switch" type="checkbox" id="themeToggle">
          <label class="form-check-label theme-toggle-label" for="themeToggle"></label>
        </div>

      <!-- Авторизация -->
      <div class="d-flex align-items-center">
        {% if user.is_authenticated %}
          <a href="{% url 'main:task_create' %}" class="btn new_task me-2">{% translate "Создать задачу" %}</a>
          <a href="{% url 'users:profile' request.user.pk %}" class="btn theme-btn-outline me-2 d-flex align-items-center user-btn">
            {% if request.user.avatar %}
              <img src="{{ request.user.avatar.url }}" alt="Avatar" class="rounded-circle me-2" style="width: 30px; height: 30px;">
            {% endif %}
            {{ request.user.username }}
          </a>

          <form action="{% url 'users:logout' %}" method="post" class="mb-0">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger exit-btn">{% translate "Выйти" %}</button>
          </form>
        {% else %}
          <a href="{% url 'users:login' %}" class="btn btn-warning">{% translate "Войти" %}</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

main/templates/includes/inc_image.html
{% load tags %}
{% load static %}
<script src="{% static 'js/fancybox.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/fancybox.css' %}"/>
{% if object.img %}
<a href="{{ object.img | mymedia }}" data-fancybox data-caption="Single image">
    <img class="w-25" alt="клик для увеличения" src="{{ object.img | mymedia }}"
         onerror="this.onerror=null; this.src='{% static '/img/no_image.jpg' %}'">
    </a>
{% elif users.avatar %}
<img class="w-100" src="{{ users.avatar | mymedia }}"
     onerror="this.onerror=null; this.src='{% static '/img/no_image.jpg' %}'">
{% else %}
<img class="w-20" src="{% static '/img/no_image.jpg' %}">
{% endif %}