config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("select2/", include("django_select2.urls")),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import (TaskAtWork, TaskClose, TaskCreateView, TaskDetailView,
                        TaskListView, TaskRefuse, TaskUpdateView, TaskWhishes,
                        ask_gemini_api, clear_context, stream_gemini)
from users.views import telegram_webhook

app_name = MainConfig.name


urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>", TaskDetailView.as_view(), name="task_detail"),
    path("task_update/<int:pk>", TaskUpdateView.as_view(), name="task_update"),
    path("task/work/<int:pk>", TaskAtWork.as_view(), name="task_at_work"),
    path("task/close/<int:pk>", TaskClose.as_view(), name="task_close"),
    path("task/whishes/<int:pk>", TaskWhishes.as_view(), name="task_whishes"),
    path("task/refuse/<int:pk>", TaskRefuse.as_view(), name="task_refuse"),
    path("webhook/", telegram_webhook, name="webhook"),
    path("ask-gemini/", ask_gemini_api, name="ask_gemini_api"),
    path("stream-gemini/", stream_gemini, name="stream_gemini"),
    path("clear-context/", clear_context, name="clear_context"),
    # path("whatsapp_webhook/", whatsapp_webhook, name="whatsapp_webhook"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (CustomLoginView, CustomPasswordChangeView,
                         RecoveryPasswordView, UserCreateView, UserProfileView,
                         UserUpdateView, developer ) # email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", CustomLoginView.as_view(template_name="login.html"), name="login"),
    path(
        "activate_account/",
        CustomLoginView.as_view(template_name="activate.html"),
        name="activate_account",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    # path("activate/<str:token>/", email_verification, name="activate"),
    path("recovery/", RecoveryPasswordView.as_view(), name="recovery"),
    path(
        "profile/<int:pk>/", UserProfileView.as_view(), name="profile"
    ),  # Для показа профиля
    path(
        "profile/update/<int:pk>/", UserUpdateView.as_view(), name="profile_update"
    ),  # Для редактирования профиля
    path(
        "profile/password_change/",
        CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("developer/", developer, name="developer"),
]

main/models.py
from django.contrib.auth.models import Group
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django_ckeditor_5.fields import CKEditor5Field

from users.models import User

NULLABLE = {"null": True, "blank": True}

STATUS_CHOICES = [
    ("new", "Создана"),
    ("work", "В работе"),
    ("complete", "Выполнена"),
    ("close", "Закрыта"),
]
CATEGORY_CHOICES = [
    ("access", "Предоставить/отключить доступ"),
    ("1c", "1С"),
    ("network", "Сеть и доступность"),
    ("directum", "Directum"),
    ("mail", "Вопросы по почте"),
    ("equipment", "Оборудование"),
    ("software", "Установка ПО"),
    ("other", "Другое"),
    ("auto_mods", "Автоматизация и доработки"),
]


class Task(models.Model):
    title = models.CharField(max_length=100, verbose_name="Тема")
    description = CKEditor5Field(
        verbose_name=_("Описание"),
        help_text=_("Введите описание"),
        config_name="extends",
        blank=True,
    )
    status = models.CharField(
        max_length=20,
        verbose_name=_("Статус заявки"),
        choices=STATUS_CHOICES,
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    start_date = models.DateTimeField(verbose_name="Дата начала выполнения", **NULLABLE)
    end_date = models.DateTimeField(
        verbose_name=_("Дата завершения выполнения"), **NULLABLE
    )
    priority = models.CharField(
        max_length=8,
        verbose_name="Приоритет",
        choices={"low": "Низкий", "medium": "Средний", "high": "Высокий"},
        **NULLABLE,
    )
    author = models.ForeignKey(
        User, verbose_name=_("автор"), on_delete=models.SET_NULL, **NULLABLE
    )
    img = models.ImageField(
        upload_to="task", **NULLABLE, verbose_name="Скриншот/фото проблемы"
    )
    file = models.FileField(upload_to="task", **NULLABLE, verbose_name=_("Файлы"))
    commentary = CKEditor5Field(verbose_name=_("Комментарий"), **NULLABLE)
    executor = models.ForeignKey(
        User,
        verbose_name=_("Исполнитель"),
        on_delete=models.SET_NULL,
        related_name="task_executor",
        **NULLABLE,
    )
    wishes = models.BooleanField(
        default=False, verbose_name=_("Утверждено"), help_text=_("Утвердить обращение")
    )
    anydesk = models.IntegerField(
        verbose_name="AnyDesk",
        help_text=_(
            "Введите номер AnyDesk для подключения. Загрузить AnyDesk можно внизу страницы."
        ),
        **NULLABLE,
    )
    coordinator = models.ForeignKey(
        User,
        verbose_name=_("Согласующий"),
        help_text=_("Укажите согласующего для утверждения заявки (При необходимости)"),
        on_delete=models.SET_NULL,
        related_name="coordinator",
        **NULLABLE,
    )
    category = models.CharField(
        max_length=50,
        verbose_name=_("Категория заявки"),
        choices=CATEGORY_CHOICES,
    )
    watcher = models.ManyToManyField(
        User,
        related_name="watcher",
        verbose_name=_("Наблюдатели"),
        help_text=_(
            "Укажите наблюдателей для заявки (При необходимости) Удерживайте “Control“)"
        ),
        blank=True,
    )

    def save(self, *args, **kwargs):
        if self.status == "work" and not self.start_date:
            self.start_date = now()
        elif self.status == "complete" and not self.end_date:
            self.end_date = now()
        if not self.executor:  # Если не указан исполнитель
            if self.category == "directum":
                try:
                    group = Group.objects.get(name="admin_directum")  # Получаем группу
                    first_user = group.user_set.order_by(
                        "id"
                    ).first()  # Берём первого пользователя
                    if first_user:
                        self.executor = first_user
                except Group.DoesNotExist:
                    pass  # Если группы нет, ничего не делаем

            elif self.category == "mail":
                try:
                    group = Group.objects.get(name="admin_mail")  # Получаем группу
                    first_user = group.user_set.order_by(
                        "id"
                    ).first()  # Берём первого пользователя
                    if first_user:
                        self.executor = first_user
                except Group.DoesNotExist:
                    pass  # Если группы нет, ничего не делаем
            elif self.category == "1c":
                try:
                    group = Group.objects.get(name="admin_1c")  # Получаем группу
                    first_user = group.user_set.order_by(
                        "id"
                    ).first()  # Берём первого пользователя
                    if first_user:
                        self.executor = first_user
                except Group.DoesNotExist:
                    pass  # Если группы нет, ничего не делаем
        super().save(*args, **kwargs)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"
        permissions = [
            ("can_edit_status_task", "Can edit status task"),
        ]

        def __str__(self):
            return self.title


class TaskComment(models.Model):
    task = models.ForeignKey(
        Task, verbose_name="Задача", on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, verbose_name="Автор", on_delete=models.SET_NULL, **NULLABLE
    )
    content = CKEditor5Field(verbose_name="", config_name="extends", blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        verbose_name = "Комментарий к задаче"
        verbose_name_plural = "Комментарии к задачам"
        ordering = ("created_at",)

        def __str__(self):
            return f"{self.author} - {self.task.title}"

main/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm
from django_ckeditor_5.widgets import CKEditor5Widget
from django_select2.forms import Select2MultipleWidget, Select2Widget

from main.models import Task, TaskComment
from users.models import User


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "description" or field_name == "content":
                continue
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class TaskForm(StyleFormMixin, ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields["description"].required = False

        if self.user and self.user.is_leader:
            # Ограничиваем список executor только пользователями с is_admin=True
            self.fields["executor"].queryset = User.objects.filter(is_admin=True)
        else:
            # Удаляем поле executor, если пользователь не руководитель
            self.fields.pop("executor")

    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get("category")
        watchers = cleaned_data.get("watcher")
        coordinator = cleaned_data.get("coordinator")
        executor = cleaned_data.get("executor")
        author = self.user

        # Проверка, что автор не является координатором или наблюдателем
        if author:
            if coordinator == author:
                raise ValidationError("Автор не может быть согласующим.")
            if watchers and author in watchers:
                raise ValidationError("Автор не может быть наблюдателем.")

        # Проверка на дублирование координатора и наблюдателей
        if coordinator and watchers and coordinator in watchers:
            raise ValidationError(
                "Пользователь не может быть одновременно наблюдателем и согласующим."
            )

        # Проверка на дублирование исполнителя в наблюдателях и координаторе
        if executor:
            if watchers and executor in watchers:
                raise ValidationError("Исполнитель не может быть наблюдателем.")
            if coordinator and executor == coordinator:
                raise ValidationError("Исполнитель не может быть согласующим.")

        if not executor:
            if category == "directum":
                if watchers:
                    for user in watchers:
                        if user.groups.filter(name="admin_directum").exists():
                            raise ValidationError(
                                f"Вы не можете добавлять наблюдателя {user} для категории 'Directum'."
                            )
                if (
                    coordinator
                    and coordinator.groups.filter(name="admin_directum").exists()
                ):
                    raise ValidationError(
                        f"Вы не можете добавлять согласующего {coordinator.username} для категории 'Directum'."
                    )

            if category == "mail":
                if watchers:
                    for user in watchers:
                        if user.groups.filter(name="admin_mail").exists():
                            raise ValidationError(
                                f"Вы не можете добавлять наблюдателя {user} для категории 'Вопросы по почте'."
                            )
                if (
                    coordinator
                    and coordinator.groups.filter(name="admin_mail").exists()
                ):
                    raise ValidationError(
                        f"Вы не можете добавлять согласующего {coordinator.username} для категории 'Вопросы по почте'."
                    )

            if category == "1c":
                if watchers:
                    for user in watchers:
                        if user.groups.filter(name="admin_1c").exists():
                            raise ValidationError(
                                f"Вы не можете добавлять наблюдателя {user} для категории '1С'."
                            )
                if coordinator and coordinator.groups.filter(name="admin_1c").exists():
                    raise ValidationError(
                        f"Вы не можете добавлять согласующего {coordinator.username} для категории '1С'."
                    )

        # if category not in ["access", "auto_mods"] and coordinator:
        #     raise ValidationError(
        #         "Согласующий не требуется для выбранной категории.")

        return cleaned_data

    class Meta:
        model = Task
        fields = (
            "category",
            "title",
            "anydesk",
            "description",
            "executor",
            "watcher",
            "coordinator",
        )
        widgets = {
            "watcher": Select2MultipleWidget(
                attrs={"data-placeholder": "Выберите наблюдателей"}
            ),
            "coordinator": Select2Widget(
                attrs={"data-placeholder": "Выберите согласующего"}
            ),
            "description": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="extends"
            ),
        }


class ModeratorTaskForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Task
        fields = (
            "executor",
            "watcher",
            "coordinator",
        )
        widgets = {
            "watcher": Select2MultipleWidget(
                attrs={"data-placeholder": "Выберите наблюдателей"}
            ),
            "coordinator": Select2Widget(
                attrs={"data-placeholder": "Выберите согласующего"}
            ),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        # Получаем текущего пользователя
        super().__init__(*args, **kwargs)

        if user and user.is_leader:
            # Ограничиваем список executor только пользователями с is_admin=True
            self.fields["executor"].queryset = User.objects.filter(is_admin=True)
        else:
            # Удаляем поле executor, если пользователь не руководитель
            self.fields.pop("executor")


class CommentaryTaskForm(StyleFormMixin, ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].required = False

    class Meta:
        model = TaskComment
        fields = ("content",)
        widgets = {
            "id": "comment-content",
            "content": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="extends"
            ),
        }

    def clean_content(self):
        content = self.cleaned_data.get("content", "").strip()
        text_only = re.sub(r"<[^>]+>", "", content).replace("&nbsp;", "").strip()
        if not text_only:
            raise forms.ValidationError("Комментарий не может быть пустым!")
        return content


class CoordinatorTaskForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Task
        fields = ("wishes", "status", "executor", "watcher")
        widgets = {
            "watcher": Select2MultipleWidget(
                attrs={"data-placeholder": "Выберите наблюдателей"}
            ),
        }

main/templates/main/partials/task_list_dynamic.html
{% load static i18n %}
{% for task in object_list %}
<a class="btn-task task {% if task.status == 'close' %}task-closed{% endif %}" data-id="{{ task.pk }}"
   href="{% url 'main:task_detail' task.pk %}">

  <div class="row text-center align-items-center btn-task-text">

    <!-- Категория и ID -->
    <div class="col-12 col-sm-1 btn-task-center">
      {% if task.category == "1c" %}
      <img src="{% static 'img/category_icon/1c.png' %}" width="20" height="20">
      {% elif task.category == "directum" %}
      <img src="{% static 'img/category_icon/directum.png' %}" width="20" height="20">
      {% elif task.category == "access" %}
      <img src="{% static 'img/category_icon/access.png' %}" width="20" height="20">
      {% elif task.category == "equipment" %}
      <img src="{% static 'img/category_icon/equipment.png' %}" width="20" height="20">
      {% elif task.category == "software" %}
      <img src="{% static 'img/category_icon/folder.png' %}" width="20" height="20">
      {% elif task.category == "mail" %}
      <img src="{% static 'img/category_icon/mail.png' %}" width="20" height="20">
      {% elif task.category == "network" %}
      <img src="{% static 'img/category_icon/network.png' %}" width="20" height="20">
      {% endif %}
      &nbsp;<strong>#{{ task.pk }}</strong>
    </div>

    <!-- Заголовок задачи -->
    <div class="col-12 col-sm-4 btn-task-center text-start">
      {{ task.title }}
    </div>

    <!-- Дата создания -->
    <div class="col-12 col-sm-2 btn-task-center">
      {{ task.created_at }}
    </div>

    <!-- Статус задачи и действия -->
    <div class="col-12 col-sm-2 d-flex justify-content-center flex-wrap gap-1 align-items-center">
  {% if task.status == 'complete' %}
  <form class="btn-task-center">
    <button class="btn btn-secondary text-white" disabled>{{ task.get_status_display }}</button>
  </form>
  {% elif task.status == 'work' %}
  <form class="btn-task-center">
    <button class="btn btn-primary text-white" disabled>{{ task.get_status_display }}</button>
  </form>
  {% elif task.status == 'new' %}
  <form class="btn-task-center">
    <button class="btn btn-success text-white" disabled>{{ task.get_status_display }}</button>
  </form>
  {% elif task.status == 'close' %}
  <form class="btn-task-center">
    <button class="btn btn-dark text-white" disabled>{{ task.get_status_display }}</button>
  </form>
  {% endif %}

  {% if task.status == "new" and perms.main.can_edit_status_task %}
  <form action="{% url 'main:task_at_work' task.pk %}" method="POST" class="task-action-form btn-task-center" data-task-id="{{ task.pk }}">
  {% csrf_token %}
  <button type="submit" class="btn btn-warning text-white">В работу</button>
</form>
  {% elif task.status == "new" and request.user.is_admin %}
  <form action="{% url 'main:task_at_work' task.pk %}" method="POST" class="btn-task-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning text-white">В работу</button>
  </form>
  {% endif %}

  {% if task.status == "work" and request.user.is_admin %}
  <form action="{% url 'main:task_close' task.pk %}" method="POST" class="btn-task-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-success text-white">{% translate "Выполнить" %}</button>
  </form>
  {% endif %}
</div>

   <!-- Автор и исполнитель -->
<div class="col-12 col-sm-3 btn-task-center">
  <form action="{% url 'users:profile' task.author.pk %}" class="btn-task-center" method="get">
    <button type="submit" class="btn btn-link user-link author-link p-0 m-0">{{ task.author }}</button>
  </form>

  {% if task.executor %}
  <div class="divider">/</div>
  <form action="{% url 'users:profile' task.executor.pk %}" class="btn-task-center" method="get">
    <button type="submit" class="btn btn-link executor-link p-0 m-0">
  {{ task.executor.username }}
</button>
  </form>
  {% endif %}
</div>
  </div>
</a>
{% empty %}
<p class="text-center theme-label py-5">{% translate "Задачи не найдены." %}</p>
{% endfor %} 
<!--Пагинация-->
<ul class="pagination" style="justify-content: center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}& {{request.GET.urlencode}}" class="page-link">{% translate "Назад" %}</a>
    </li>
    <li class="page-item">
        <a href="?page=1& {{request.GET.urlencode}}" class="page-link">1</a></li>
    {% endif %}
    <li class="page-item active">
        <span class="page-link">
{{ page_obj.number }}
            <span class="sr-only"></span>
        </span>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link"
                             href="?page={{ page_obj.next_page_number }}& {{request.GET.urlencode}}">{{page_obj.next_page_number}}</a>
    </li>
    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}& {{request.GET.urlencode}}"
                             class="page-link">{% translate "Вперед" %}</a></li>
    {% endif %}
</ul>